version: '3.8'

services:
  ai-blog-generator:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped